"""Materialises the repository scaffold (community files, workflows, hooks)."""

from __future__ import annotations

import datetime as dt
from dataclasses import dataclass, field
from pathlib import Path
from string import Template
from typing import Callable

from .config import Config

TEMPLATE_ROOT = Path(__file__).parent / "templates" / "scaffold"
HOOK_FILES = (".githooks/commit-msg", ".githooks/pre-push")

# component -> list of files (relative path inside the repository)
COMPONENTS: dict[str, list[str]] = {
    "readme": ["README.md"],
    "gitignore": [".gitignore"],
    "license": ["LICENSE"],
    "editorconfig": [".editorconfig"],
    "gitattributes": [".gitattributes"],
    "codeowners": [".github/CODEOWNERS"],
    "pr_template": [".github/PULL_REQUEST_TEMPLATE.md"],
    "issue_templates": [
        ".github/ISSUE_TEMPLATE/bug_report.yml",
        ".github/ISSUE_TEMPLATE/feature_request.yml",
        ".github/ISSUE_TEMPLATE/config.yml",
    ],
    "contributing": ["CONTRIBUTING.md"],
    "workflows": [".github/workflows/conventions.yml"],
    "githooks": [".githooks/commit-msg", ".githooks/pre-push", ".githooks/README.md"],
}

_FALLBACK_GITIGNORE = """# OS / editor
.DS_Store
Thumbs.db
*.swp
.idea/
.vscode/
# Environment
.env
.env.*
!.env.example
# Build / logs
dist/
build/
*.log
"""


@dataclass
class ScaffoldResult:
    written: list[Path] = field(default_factory=list)
    skipped: list[Path] = field(default_factory=list)
    executable: list[str] = field(default_factory=list)

    @property
    def changed(self) -> bool:
        return bool(self.written)


def template_variables(cfg: Config, repo_name: str) -> dict[str, str]:
    conv = cfg.conventions
    return {
        "owner": cfg.owner,
        "repo": repo_name,
        "default_branch": cfg.repo.default_branch,
        "branch_pattern": conv.branch_pattern,
        "branch_types": ", ".join(conv.branch_types),
        "protected_branches": " ".join(conv.protected_branches),
        "commit_types": ", ".join(conv.commit_types),
        "commit_types_alternation": "|".join(conv.commit_types),
        "commit_subject_max": str(conv.commit_subject_max),
        "tag_prefix": conv.tag_prefix,
        "year": str(dt.date.today().year),
        "codeowners": render_codeowners(cfg),
    }


def render_codeowners(cfg: Config) -> str:
    lines = [
        "# CODEOWNERS - reviewers automatically requested for matching paths.",
        "# Generated by gitteam from gitteam.yaml (scaffold.codeowners).",
        "",
    ]
    for pattern, owners in cfg.scaffold.codeowners.items():
        expanded = " ".join(owner.replace("{owner}", cfg.owner) for owner in owners)
        lines.append(f"{pattern:<24} {expanded}")
    return "\n".join(lines) + "\n"


def render_template(relative: str, variables: dict[str, str]) -> str:
    source = (TEMPLATE_ROOT / relative).read_text(encoding="utf-8")
    return Template(source).safe_substitute(variables)


def materialize(
    workdir: Path,
    cfg: Config,
    repo_name: str,
    *,
    gitignore_source: Callable[[str], str | None] | None = None,
    license_source: Callable[[str], str | None] | None = None,
    components: list[str] | None = None,
    force: bool = False,
    dry_run: bool = False,
) -> ScaffoldResult:
    """Write scaffold files into ``workdir``. Existing files are kept unless ``force``."""
    result = ScaffoldResult()
    variables = template_variables(cfg, repo_name)
    selected = components if components is not None else cfg.scaffold.include
    for component in selected:
        files = COMPONENTS.get(component)
        if files is None:
            raise ValueError(f"unknown scaffold component '{component}' (known: {', '.join(COMPONENTS)})")
        for relative in files:
            target = workdir / relative
            if target.exists() and not force:
                result.skipped.append(target)
                continue
            content = _content_for(relative, cfg, variables, gitignore_source, license_source)
            if content is None:
                result.skipped.append(target)
                continue
            if not dry_run:
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_text(content, encoding="utf-8", newline="\n")
            result.written.append(target)
            if relative in HOOK_FILES:
                result.executable.append(relative)
    return result


def _content_for(
    relative: str,
    cfg: Config,
    variables: dict[str, str],
    gitignore_source: Callable[[str], str | None] | None,
    license_source: Callable[[str], str | None] | None,
) -> str | None:
    if relative == ".gitignore":
        parts: list[str] = []
        for name in cfg.repo.gitignore_templates:
            body = gitignore_source(name) if gitignore_source else None
            if body:
                parts.append(f"# ---- {name} (github/gitignore) ----\n{body.strip()}\n")
        parts.append("# ---- common ----\n" + _FALLBACK_GITIGNORE)
        return "\n".join(parts)
    if relative == "LICENSE":
        if not cfg.repo.license:
            return None
        body = license_source(cfg.repo.license) if license_source else None
        if not body:
            return None
        return (
            body.replace("[year]", variables["year"])
            .replace("[yyyy]", variables["year"])
            .replace("[fullname]", cfg.owner)
            .replace("[name of copyright owner]", cfg.owner)
        )
    if relative == ".github/CODEOWNERS":
        return variables["codeowners"]
    return render_template(relative, variables)
